/**
 * File: renderer/components/quiz/quizTypes.ts
 * Purpose: Central TypeScript contracts for quiz and flashcard content generated by the LLM.
 * Summary of changes:
 * - Added strongly typed schemas that mirror the agreed JSON contract.
 * - Added helper union types for quiz items and flashcards.
 * Author: Malek Kchaou
 * Git-history contributors: Malek Kchaou
 * Date: 2026-04-12
 * Note: Keep this file aligned with the quiz-generation prompt contract.
 */

export type QuizDifficulty = "easy" | "medium" | "hard";
export type QuizRootType = "quiz" | "flashcards";

export interface QuizMeta {
    topic: string;
    difficulty: QuizDifficulty;
    total: number;
}

export interface MultipleChoiceItem {
    id: number;
    kind: "multiple_choice";
    question: string;
    options: [string, string, string, string];
    answer: string;
}

export interface TrueFalseItem {
    id: number;
    kind: "true_false";
    question: string;
    answer: boolean;
}

export interface MatchingPair {
    prompt: string;
    match: string;
}

export interface MatchingItem {
    id: number;
    kind: "matching";
    question: string;
    pairs: MatchingPair[];
}

export interface FillInBlankItem {
    id: number;
    kind: "fill_in_blank";
    question: string;
    blanks: string[];
}

export interface DragAndDropItem {
    id: number;
    kind: "drag_and_drop";
    question: string;
    items: string[];
    answer: string[];
}

export interface FreeResponseItem {
    id: number;
    kind: "free_response";
    question: string;
    rubric: string;
}

export interface FlashcardItem {
    id: number;
    kind: "flashcard";
    front: string;
    back: string;
}

export type QuizItem =
    | MultipleChoiceItem
    | TrueFalseItem
    | MatchingItem
    | FillInBlankItem
    | DragAndDropItem
    | FreeResponseItem;

export interface QuizDocument {
    type: "quiz";
    meta: QuizMeta;
    items: QuizItem[];
}

export interface FlashcardsDocument {
    type: "flashcards";
    meta: QuizMeta;
    items: FlashcardItem[];
}

export type QuizPayload = QuizDocument | FlashcardsDocument;